#!/bin/bash
# Submitter for the linear-peptide mixing pipeline. Calls sbatch and nothing else.
#
#   bash scripts/submit_lp_mixing.sh --submit <stage> [options]
#
# Stages:
#   data          CPU   PepBench+ProtFrag -> processed PDBs + mixed metadata
#   verify        CPU   prove the LINEAR token + sampler work on the real data
#   ae            GPU   the shared VAE on CPSea + linear peptides
#   flow-mix      GPU   flow arm: CPSea + 25% linear
#   flow-control  GPU   flow arm: CPSea only (the control)
#   all           the whole chain: data -> verify -> ae -> {flow-mix, flow-control}
#
# The two flow arms are SIBLINGS, both depending only on the AE job, so they queue
# concurrently instead of one waiting behind the other. They are also the comparison, so
# submitting one without the other produces an uninterpretable result.
#
# Writes ONE timestamped env file per submission and passes its PATH as a positional
# argument. Never `sbatch --export`: any explicit export list (--export=ALL,K=v and
# --export=NONE alike) sets SLURM_GET_USER_ENV=1, slurmd then fails to rebuild the login
# environment on the compute node, and the job is requeued and HELD, stranding every
# dependent on Dependency.
#
# Pick the GPU with --gpu-nodelist from a fresh `myfree`; the default partition assumes an
# a6000 is free on `general`.

set -euo pipefail
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO"

STAGE=""; DRYRUN=0
GPU_PARTITION="general"; GPU_GRES="gpu:a6000:1"; GPU_NODELIST=""
CPU_PARTITION="cpu"
AE_TIME="2-00:00:00"; FLOW_TIME="2-00:00:00"; DATA_TIME="08:00:00"
SMOKE=0
declare -a EXTRA_ENV=()

usage() { sed -n '2,26p' "$0"; exit "${1:-0}"; }

while [[ $# -gt 0 ]]; do
  case "$1" in
    --submit)          STAGE="$2";          shift 2 ;;
    --gpu-partition)   GPU_PARTITION="$2";  shift 2 ;;
    --gpu-gres)        GPU_GRES="$2";       shift 2 ;;
    --gpu-nodelist)    GPU_NODELIST="$2";   shift 2 ;;
    --cpu-partition)   CPU_PARTITION="$2";  shift 2 ;;
    --ae-time)         AE_TIME="$2";        shift 2 ;;
    --flow-time)       FLOW_TIME="$2";      shift 2 ;;
    --data-time)       DATA_TIME="$2";      shift 2 ;;
    # Anything of the form VAR=value is written into the env file, so every knob in
    # scripts/_lp_mixing_preamble.sh is settable without editing a script.
    --set)             EXTRA_ENV+=("$2");   shift 2 ;;
    --smoke)           SMOKE=1;             shift ;;
    --dry-run)         DRYRUN=1;            shift ;;
    -h|--help)         usage 0 ;;
    *) echo "unknown arg: $1" >&2; usage 1 >&2 ;;
  esac
done
[[ -n "$STAGE" ]] || { echo "FATAL: --submit <stage> is required" >&2; usage 1 >&2; }

STAMP="$(date +%Y%m%d_%H%M%S)"
ENV_DIR="${REPO}/env_files"; mkdir -p "$ENV_DIR" slurm_logs
ENV_FILE="${ENV_DIR}/lp_mixing_${STAMP}.env"
{
  echo "# generated by submit_lp_mixing.sh at ${STAMP}"
  echo "REPO=${REPO}"
  echo "SMOKE=${SMOKE}"
  for kv in "${EXTRA_ENV[@]+"${EXTRA_ENV[@]}"}"; do echo "$kv"; done
} > "$ENV_FILE"
echo "env file: $ENV_FILE"
sed 's/^/  /' "$ENV_FILE"

# Submitting from inside an allocation would otherwise leak this job's SLURM_* into the
# child, which confuses srun and the resume logic.
for v in $(compgen -v | grep '^SLURM_' || true); do unset "$v" || true; done

NODELIST_ARG=(); [[ -n "$GPU_NODELIST" ]] && NODELIST_ARG=(--nodelist="$GPU_NODELIST")

submit() {  # submit <description> <sbatch args...>
  local desc="$1"; shift
  if [[ $DRYRUN -eq 1 ]]; then
    # To stderr: stdout is the job id this function returns to its caller.
    { printf 'DRY-RUN %-14s sbatch' "$desc"; printf ' %q' "$@"; printf '\n'; } >&2
    echo "999999"
    return
  fi
  local out; out="$(sbatch "$@")"
  echo "$desc: $out" >&2
  awk '{print $NF}' <<<"$out"
}

DATA_JID=""; VERIFY_JID=""; AE_JID=""

if [[ "$STAGE" == "data" || "$STAGE" == "all" ]]; then
  DATA_JID="$(submit data \
    --partition="$CPU_PARTITION" --time="$DATA_TIME" \
    scripts/lp_build_data.sbatch "$ENV_FILE")"
fi

if [[ "$STAGE" == "verify" || "$STAGE" == "all" ]]; then
  DEP=(); [[ -n "$DATA_JID" ]] && DEP=(--dependency=afterok:"$DATA_JID")
  VERIFY_JID="$(submit verify \
    --partition="$CPU_PARTITION" --time=01:00:00 \
    "${DEP[@]}" \
    scripts/lp_verify.sbatch "$ENV_FILE")"
fi

if [[ "$STAGE" == "ae" || "$STAGE" == "all" ]]; then
  # Behind verify, not merely data: the AE is a multi-day run, and the cheapest moment to
  # find out the topology token is mis-wired is before it starts rather than after.
  DEP=()
  if   [[ -n "$VERIFY_JID" ]]; then DEP=(--dependency=afterok:"$VERIFY_JID")
  elif [[ -n "$DATA_JID"   ]]; then DEP=(--dependency=afterok:"$DATA_JID"); fi
  AE_JID="$(submit ae \
    --partition="$GPU_PARTITION" --gres="$GPU_GRES" --time="$AE_TIME" \
    "${NODELIST_ARG[@]}" "${DEP[@]}" \
    scripts/lp_train_ae.sbatch "$ENV_FILE")"
fi

for arm in mix control; do
  case "$STAGE" in
    all) ;;
    flow-mix)     [[ "$arm" == mix ]]     || continue ;;
    flow-control) [[ "$arm" == control ]] || continue ;;
    *) continue ;;
  esac
  DEP=(); [[ -n "$AE_JID" ]] && DEP=(--dependency=afterok:"$AE_JID")
  submit "flow-$arm" \
    --partition="$GPU_PARTITION" --gres="$GPU_GRES" --time="$FLOW_TIME" \
    "${NODELIST_ARG[@]}" "${DEP[@]}" \
    scripts/lp_train_flow.sbatch "$ENV_FILE" "ARM=$arm" >/dev/null
done

case "$STAGE" in
  data|verify|ae|flow-mix|flow-control|all) ;;
  *) echo "FATAL: unknown stage '$STAGE'" >&2; usage 1 >&2 ;;
esac
echo "submitted stage: $STAGE"
